/**
 * `cortextos detect-chat-id` — bounded Telegram chat_id auto-capture.
 *
 * The single fiddliest step in operator install (per the Brett friction report,
 * 2026-06-01): turning a fresh @BotFather token into the numeric chat_id the
 * agent needs. The legacy manual path was "curl getUpdates | jq '.result[-1]...'",
 * which fails silently when the operator hasn't messaged the bot yet, returns
 * `null`, and gives no guidance.
 *
 * This command:
 *   1. Takes a BotFather BOT_TOKEN (flag or interactive prompt — never hardcoded).
 *   2. Verifies it with getMe and prints the bot @username so the operator knows
 *      which bot to message.
 *   3. Polls getUpdates in a BOUNDED loop until the operator messages the bot,
 *      auto-capturing chat_id + ALLOWED_USER the moment a real (non-bot) message
 *      lands. Graceful, explicit timeout — never hangs forever.
 *   4. Optionally writes BOT_TOKEN + CHAT_ID + ALLOWED_USER to an agent's .env
 *      (merging with existing keys, chmod 600) when --agent is passed; otherwise
 *      just prints the captured values for the caller to consume.
 *
 * Designed to be both interactive (operator at a terminal) and scriptable
 * (--token + --agent + --yes). Errors are owned in conversation: invalid token,
 * expired/revoked token, and no-messages-before-timeout each print what went
 * wrong and what to do, and exit non-zero without leaving partial state.
 */
import { Command } from 'commander';
import { createInterface, type Interface } from 'readline';
import { existsSync, readdirSync, readFileSync, writeFileSync, chmodSync } from 'fs';
import { join } from 'path';
import { TelegramAPI } from '../telegram/api.js';

function rl(): Interface {
  return createInterface({ input: process.stdin, output: process.stdout });
}

function ask(iface: Interface, question: string): Promise<string> {
  return new Promise(resolve => iface.question(question, answer => resolve(answer.trim())));
}

function findProjectRoot(): string {
  const candidates = [
    process.env.CORTEXTOS_DIR,
    process.env.CTX_FRAMEWORK_ROOT,
    process.env.CTX_PROJECT_ROOT,
    process.cwd(),
  ].filter(Boolean) as string[];
  for (const c of candidates) {
    if (existsSync(join(c, 'orgs'))) return c;
  }
  return process.cwd();
}

function resolveAgentDir(projectRoot: string, agentName: string, org?: string): { dir: string; org: string } | null {
  const orgsDir = join(projectRoot, 'orgs');
  if (!existsSync(orgsDir)) return null;

  if (org) {
    const dir = join(orgsDir, org, 'agents', agentName);
    return existsSync(dir) ? { dir, org } : null;
  }

  const orgs = readdirSync(orgsDir, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);
  const matches = orgs.filter(o => existsSync(join(orgsDir, o, 'agents', agentName)));
  if (matches.length === 1) {
    return { dir: join(orgsDir, matches[0], 'agents', agentName), org: matches[0] };
  }
  if (matches.length > 1) {
    console.error(`  Agent "${agentName}" exists under multiple orgs: ${matches.join(', ')}. Pass --org <name> to disambiguate.`);
    return null;
  }
  return null;
}

function writeEnv(envPath: string, values: Record<string, string>, originalContent: string | null): void {
  // Preserve original comments + non-key lines when an .env already exists;
  // only replace lines for keys we are setting. Mirrors `bot create` so both
  // entry points produce the same on-disk shape.
  const setKeys = new Set(Object.keys(values));
  const output: string[] = [];

  if (originalContent !== null) {
    const seenKeys = new Set<string>();
    for (const line of originalContent.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) {
        output.push(line);
        continue;
      }
      const eq = trimmed.indexOf('=');
      const key = eq > 0 ? trimmed.slice(0, eq).trim() : '';
      if (key && setKeys.has(key)) {
        output.push(`${key}=${values[key]}`);
        seenKeys.add(key);
      } else {
        output.push(line);
      }
    }
    for (const k of setKeys) {
      if (!seenKeys.has(k)) output.push(`${k}=${values[k]}`);
    }
  } else {
    output.push('# Agent environment — Telegram bot credentials');
    output.push('# Generated by `cortextos detect-chat-id`');
    output.push('');
    for (const k of Object.keys(values)) output.push(`${k}=${values[k]}`);
  }

  let content = output.join('\n');
  if (!content.endsWith('\n')) content += '\n';
  writeFileSync(envPath, content, 'utf-8');
  try { chmodSync(envPath, 0o600); } catch { /* ignore on Windows */ }
}

interface CapturedUser {
  chatId: number;
  fromId: number;
  username?: string;
  firstName?: string;
}

/**
 * Drain one getUpdates batch and pick the most recent /start (or any message)
 * from a non-bot user. Returns null when no qualifying message is present so
 * the polling loop keeps waiting. Telegram returns nothing for chats the bot
 * has never seen — the operator must message the bot first.
 */
export function pickUserFromUpdates(updates: any): CapturedUser | null {
  const results: any[] = (updates && Array.isArray(updates.result)) ? updates.result : [];
  if (results.length === 0) return null;

  const messages = results.map(u => u.message).filter(Boolean).reverse();
  const startMatch = messages.find(m => typeof m.text === 'string' && m.text.trim().startsWith('/start'));
  const chosen = startMatch ?? messages[0];
  if (!chosen || !chosen.chat) return null;
  const from = chosen.from ?? {};
  if (from.is_bot) return null;
  return {
    chatId: chosen.chat.id,
    fromId: from.id,
    username: from.username,
    firstName: from.first_name,
  };
}

/**
 * Poll getUpdates until a real user message lands or the deadline passes.
 * Bounded by `timeoutSec`; polls every `intervalSec`. Returns the captured
 * user, or null on timeout. getUpdates transport errors are tolerated and
 * retried until the deadline (transient network blips shouldn't abort the
 * whole capture), but the last error is surfaced if we time out having only
 * ever errored.
 */
export interface UpdatePoller {
  getUpdates(offset: number, timeout?: number): Promise<any>;
}

export async function pollForUser(
  api: UpdatePoller,
  timeoutSec: number,
  intervalSec: number,
): Promise<{ user: CapturedUser | null; lastError: string | null }> {
  const deadline = Date.now() + timeoutSec * 1000;
  let lastError: string | null = null;
  let sawAnySuccess = false;

  while (Date.now() < deadline) {
    try {
      const updates = await api.getUpdates(0, 1);
      sawAnySuccess = true;
      const user = pickUserFromUpdates(updates);
      if (user) return { user, lastError: null };
    } catch (err) {
      lastError = err instanceof Error ? err.message : String(err);
      // A token-auth failure (401 Unauthorized) won't recover by retrying —
      // bail immediately so the operator fixes the token instead of waiting
      // out the full timeout.
      if (/unauthorized|not found/i.test(lastError)) {
        return { user: null, lastError };
      }
    }
    const remaining = deadline - Date.now();
    if (remaining <= 0) break;
    await new Promise(r => setTimeout(r, Math.min(intervalSec * 1000, remaining)));
  }

  return { user: null, lastError: sawAnySuccess ? null : lastError };
}

interface DetectOptions {
  token?: string;
  agent?: string;
  org?: string;
  timeout: string;
  interval: string;
  yes?: boolean;
  json?: boolean;
}

async function detectChatId(opts: DetectOptions): Promise<void> {
  const timeoutSec = Math.max(5, parseInt(opts.timeout, 10) || 120);
  const intervalSec = Math.max(1, parseInt(opts.interval, 10) || 2);

  // Resolve the .env target up front (if --agent) so we fail fast on a bad
  // agent name before asking the operator to do any Telegram work.
  let envTarget: { dir: string; org: string; envPath: string; originalContent: string | null } | null = null;
  if (opts.agent) {
    const projectRoot = findProjectRoot();
    const resolved = resolveAgentDir(projectRoot, opts.agent, opts.org);
    if (!resolved) {
      console.error(`Error: agent "${opts.agent}" not found under any org in ${projectRoot}/orgs/`);
      console.error('Add it first with: cortextos add-agent ' + opts.agent + ' --org <org>');
      process.exit(1);
    }
    const envPath = join(resolved.dir, '.env');
    envTarget = {
      dir: resolved.dir,
      org: resolved.org,
      envPath,
      originalContent: existsSync(envPath) ? readFileSync(envPath, 'utf-8') : null,
    };
  }

  // Acquire the token: flag, env var, or interactive prompt. Never hardcoded.
  let iface: Interface | null = null;
  let botToken = opts.token || process.env.BOT_TOKEN || '';
  if (!botToken) {
    iface = rl();
    console.log('');
    console.log('Paste the BOT_TOKEN @BotFather gave you (it looks like 123456789:AA...).');
    botToken = await ask(iface, 'BOT_TOKEN: ');
  }

  try {
    if (!botToken) {
      console.error('  Error: BOT_TOKEN is required.');
      process.exit(1);
    }
    if (!/^\d+:[A-Za-z0-9_-]+$/.test(botToken)) {
      console.error('  Error: BOT_TOKEN does not look like a Telegram token (expected <digits>:<chars>).');
      console.error('  Re-check @BotFather and run this command again.');
      process.exit(1);
    }

    const api = new TelegramAPI(botToken);

    // Verify the token + surface the bot @username so the operator knows which
    // bot to message.
    let me: any;
    try {
      me = await api.getMe();
    } catch (err) {
      console.error(`  Telegram getMe failed: ${err instanceof Error ? err.message : String(err)}`);
      console.error('  This usually means the token is wrong, revoked, or you have no internet.');
      console.error('  Fix the token at @BotFather (or check your connection), then re-run.');
      process.exit(1);
    }
    const botUsername: string = me?.result?.username ?? '';
    const botId: number = me?.result?.id;
    if (!botUsername || !botId) {
      console.error('  Telegram getMe returned an unexpected shape — cannot proceed.');
      console.error('  Raw response: ' + JSON.stringify(me).slice(0, 200));
      process.exit(1);
    }

    if (!opts.json) {
      console.log('');
      console.log(`  Verified: bot is @${botUsername} (id ${botId}).`);
      console.log('');
      console.log(`  Now open Telegram, search for @${botUsername}, and send /start.`);
      console.log('  Do it from the account that should control this agent.');
      console.log(`  Waiting up to ${timeoutSec}s for your message...`);
    }

    const { user, lastError } = await pollForUser(api, timeoutSec, intervalSec);

    if (!user) {
      if (lastError && /unauthorized/i.test(lastError)) {
        console.error('');
        console.error('  Telegram rejected the token (Unauthorized) — it is wrong or revoked.');
        console.error('  Get a fresh token from @BotFather and re-run.');
        process.exit(1);
      }
      console.error('');
      console.error(`  No message arrived within ${timeoutSec}s.`);
      console.error(`  Make sure you sent /start to @${botUsername} from your own account`);
      console.error('  (not a channel, not another bot), then re-run this command.');
      if (lastError) console.error(`  (last network error: ${lastError})`);
      process.exit(1);
    }

    const chatId = String(user.chatId);
    const allowedUser = user.username || String(user.fromId);
    const displayName = user.firstName || user.username || `id ${user.fromId}`;

    if (opts.json) {
      // Machine-consumable output for scripted install flows.
      process.stdout.write(JSON.stringify({
        bot_username: botUsername,
        chat_id: chatId,
        allowed_user: allowedUser,
        from_id: user.fromId,
      }) + '\n');
    } else {
      console.log('');
      console.log(`  Captured: chat_id=${chatId} allowed_user=${allowedUser} (${displayName})`);
    }

    if (envTarget) {
      if (!opts.yes && !opts.json && iface) {
        const confirm = await ask(iface, `  Write to ${envTarget.envPath}? [Y/n]: `);
        if (confirm && confirm.toLowerCase().startsWith('n')) {
          console.log('  Aborted — no file written.');
          process.exit(0);
        }
      }
      writeEnv(envTarget.envPath, {
        BOT_TOKEN: botToken,
        CHAT_ID: chatId,
        ALLOWED_USER: allowedUser,
      }, envTarget.originalContent);
      if (!opts.json) {
        console.log('');
        console.log(`  Wrote BOT_TOKEN + CHAT_ID + ALLOWED_USER to ${envTarget.envPath} (chmod 600).`);
        console.log(`  Next: cortextos start ${opts.agent}`);
      }
    }
  } finally {
    if (iface) iface.close();
  }
}

export const detectChatIdCommand = new Command('detect-chat-id')
  .description('Capture a Telegram chat_id by polling getUpdates until you message the bot (foolproofs the install bot-ID step)')
  .option('--token <token>', 'BotFather BOT_TOKEN (else BOT_TOKEN env var, else prompts)')
  .option('--agent <name>', 'Write BOT_TOKEN+CHAT_ID+ALLOWED_USER to this agent\'s .env (else just prints)')
  .option('--org <org>', 'Organization name (auto-detected if only one)')
  .option('--timeout <seconds>', 'Max seconds to wait for your message', '120')
  .option('--interval <seconds>', 'Seconds between getUpdates polls', '2')
  .option('--json', 'Emit captured values as JSON (for scripted install flows)')
  .option('-y, --yes', 'Skip the .env write confirmation prompt')
  .action(detectChatId);
